---

#---- SYSTEM CONFIGURATION

#TODO: change and move to vault - they are in ssm now
filebeat_user: logstash
filebeat_password: "{{ lookup('aws_ssm', '/es/auth/telegraf_password', decrypt=true, ) }}"
# File that ansible will use for logs
ansible_player_logfile: /var/log/ansible_player*.log
filebeat_version: 7.9.2
filebeat_host: internal-es-system-data.lma-dev.wbx2.com:443
stage: dev
tag: LMA

NameServer: 8.8.8.8