---

#---- SYSTEM CONFIGURATION

#TODO: change and move to vault - they are in ssm now
filebeat_user: logstash
filebeat_password: "{{ lookup('aws_ssm', '/elasticsearch/auth/logstash', decrypt=true, ) }}"
# File that ansible will use for logs
ansible_player_logfile: /var/log/ansible_player*.log
filebeat_version: 7.9.2
filebeat_host: "{{ instance_ec2_facts['instances'][0]['tags']['log_hostname'] }}:443"
filebeat_index: "{{ instance_ec2_facts['instances'][0]['tags']['log_index'] }}"

domainname: "{{ instance_ec2_facts['instances'][0]['tags']['dns_root_domain_name'] }}"
hostname: "{{ instance_ec2_facts['instances'][0]['tags']['hostname'] }}"
region: "{{ ansible_ec2_placement_region }}"
stage: "{{ instance_ec2_facts['instances'][0]['tags']['stage'] }}"
tag: LMA
owner: "no-reply@cisco.com"
target: "elasticsearch, aggregate"


NameServer1: 208.67.222.222
NameServer2: 208.67.220.220
NameServer3: 8.8.8.8
