#!/bin/bash
export HOME=/root
#export AWS_DEFAULT_REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep -oP '\"region\"[[:space:]]*:[[:space:]]*\"\K[^\"]+'`
#TODO fix region hardcode
export AWS_DEFAULT_REGION=us-east-1
#if we don't export the path then some packages (filebeat) have problems with the install
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
#TODO this doesnt pull the playbooks for the instance correctly
PLAYBOOKS=`aws ec2 describe-tags --filters "Name=resource-id,Values=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)" --filters "Name=key,Values=ansible_playbooks" |jq -r .Tags[0].Value`
git config --global credential.helper '!aws codecommit credential-helper $@'
git config --global credential.UseHttpPath true
for playbook in $PLAYBOOKS; do
  REPO=`echo $playbook | awk -F: '{print $1}'`
  REF=`echo $playbook | awk -F: '{print $2}'`
  FILE=`echo $playbook | awk -F: '{print $3}'`
  ansible-pull --sleep 60 -i /var/lib/ansible/local/$REPO/hosts -d /var/lib/ansible/local/$REPO -U https://git-codecommit.us-east-1.amazonaws.com/v1/repos/ansible-$REPO -C $REF $FILE >>/var/log/ansible_player_$REPO.log 2>&1
done
