---
# handlers 

- name: chrony restart
  service: name=chrony state=restarted
  become: yes

- name: telegraf restart
  service: name=telegraf state=restarted
  become: yes

- name: syslog restart
  service: name=syslog state=restarted
  become: yes

- name: filebeat restart
  service: name=filebeat state=restarted
  become: yes
